import { expect, type Page } from '@playwright/test';
import { test } from '../helpers/update-release';
import { cp } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { OLL_CASES, PLL_CASES } from '../../src/data';
import { canonicalText } from '../../src/cube/notation';
import type { TrainerBackupV1 } from '../../src/store/records';
import { lowerIndices, normalize, replay, solved } from '../helpers/case-oracle';
async function dataPanel(page: Page) { await page.getByRole('button', { name: 'Help', exact: true }).click(); await page.getByRole('button', { name: 'Local data and offline setup' }).click(); }
async function setup(page: Page) {
  await page.goto('/'); await dataPanel(page); await page.getByRole('button', { name: 'Set up / retry review' }).click();
  await expect(page.getByRole('button', { name: 'Reload to finish setup' })).toBeVisible({ timeout: 30000 }); await page.getByRole('button', { name: 'Reload to finish setup' }).click();
  await expect(page.getByRole('button', { name: /OLL ready.*PLL ready/ })).toBeVisible({ timeout: 30000 });
}
async function choose(page: Page, trainer: 'oll' | 'pll', count?: number, inspection = 'untimed') {
  await page.getByRole('combobox', { name: 'Trainer', exact: true }).selectOption(trainer); await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await page.getByRole('combobox', { name: 'Time Attack mode', exact: true }).selectOption('recognition'); await page.getByRole('combobox', { name: 'Setup pre-U', exact: true }).selectOption('2'); await page.getByRole('combobox', { name: 'Setup yaw', exact: true }).selectOption('3'); await page.getByRole('combobox', { name: 'Inspection', exact: true }).selectOption(inspection);
  if (count) { await page.getByRole('button', { name: 'Clear case selection' }).click(); await expect(page.getByRole('button', { name: 'Save settings' })).toBeDisabled(); for (const entry of (trainer === 'oll' ? OLL_CASES : PLL_CASES).slice(0, count)) await page.getByRole('checkbox', { name: `${trainer.toUpperCase()} ${entry.label} ·`, exact: false }).check(); }
  await page.getByRole('button', { name: 'Save settings' }).click(); await expect(page.getByText('Settings saved on this device.')).toBeVisible(); await page.getByRole('button', { name: 'Close dialog' }).click();
}
async function start(page: Page, trainer: 'oll' | 'pll') { await page.getByRole('button', { name: `Start ${trainer.toUpperCase()} run`, exact: true }).click(); await expect(page.getByRole('button', { name: 'Present next rep' })).toBeVisible({ timeout: 30000 }); }
async function present(page: Page) { await expect(page.getByRole('button', { name: 'Present next rep' })).toBeDisabled(); await page.getByRole('checkbox', { name: /My F2L|My cube is fully solved/ }).check(); await page.getByRole('button', { name: 'Present next rep', exact: true }).click(); await expect(page.locator('.timer-input')).toBeEnabled(); }
async function execute(page: Page, accelerated = false) {
  await page.keyboard.down('Space'); if (accelerated) await page.clock.runFor(330); else await page.waitForTimeout(330); await page.keyboard.up('Space'); await expect(page.getByRole('status').filter({ hasText: 'Tap to stop' })).toBeVisible();
  if (accelerated) await page.clock.runFor(1234); await page.keyboard.press('Space'); await expect(page.getByRole('status').filter({ hasText: 'Saved on this device' })).toBeVisible(); if (accelerated) await page.clock.runFor(300); else await page.waitForTimeout(260);
}
async function backup(page: Page) { await dataPanel(page); const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'Download current backup' }).click(); const path = await (await download).path(), bytes = readFileSync(path ?? ''), value: TrainerBackupV1 = JSON.parse(bytes.toString()); await page.getByRole('button', { name: 'Close dialog' }).click(); return { value, bytes }; }
async function hidden(page: Page) {
  const output = `${await page.locator('main').innerText()}\n${await page.locator('main').ariaSnapshot()}`;
  expect(output).not.toMatch(/oll:speeden|pll:speeden|Frozen guidance:|Speeden source|\bOLL \d+\b|\bPLL (Aa|Ab|T|H|Ua|Ub)\b/); expect(await page.locator('.f2l-guidance').count()).toBe(0); expect(await page.locator('twisty-player').count()).toBe(0);
}
for (const trainer of ['oll', 'pll'] as const) test(`genuine full ${trainer.toUpperCase()} run cold offline with accelerated production timer and complete frozen links`, async ({ page, context, browser }) => {
  test.setTimeout(180000);
  await setup(page); await context.setOffline(true); await page.close(); const cold = await context.newPage(), failures: string[] = []; cold.on('requestfailed', (request) => failures.push(request.url()));
  await cold.goto(`/cold-unopened-${trainer}`); await expect(cold.getByRole('button', { name: /OLL ready.*PLL ready/ })).toBeVisible({ timeout: 30000 }); await choose(cold, trainer); await start(cold, trainer);
  const planned = await backup(cold), run = planned.value.runs[0], count = trainer === 'oll' ? 57 : 21; expect(run?.repPlan).toHaveLength(count); expect(planned.value.attempts).toEqual([]);
  await cold.clock.install({ time: new Date(Date.now() + 1000) });
  for (let index = 0; index < count; index++) {
    await present(cold); await hidden(cold); if (index === 0) { for (const [width, height] of [[320, 640], [390, 844], [1440, 900]] as const) { await cold.setViewportSize({ width, height }); const box = await cold.locator('.timer-input').boundingBox(); if (!box) throw Error('Missing timer.'); expect(box.y + box.height).toBeLessThanOrEqual(height); expect(await cold.evaluate(() => document.documentElement.scrollWidth)).toBe(width); } }
    await execute(cold, true); await expect(cold.locator('.f2l-guidance')).toBeVisible(); await cold.getByRole('button', { name: 'Next challenge' }).click();
  }
  await cold.getByText('Run summary', { exact: true }).click(); await expect(cold.getByRole('region', { name: 'Time Attack run results' })).toContainText(`${count} completed · 0 DNF · 0 skipped · 0 interrupted`); await expect(cold.getByRole('region', { name: 'Time Attack run results' })).toContainText('Compatible set PB:');
  const saved = await backup(cold), complete = saved.value.runs[0]; expect(saved.value.attempts).toHaveLength(count); expect(complete).toMatchObject({ status: 'complete', cursor: count, presented: false, interruptions: [] }); expect(new Set(saved.value.attempts.map((attempt) => attempt.repIndex)).size).toBe(count);
  for (const attempt of saved.value.attempts) { expect(attempt.runId).toBe(run?.id); expect(attempt.timing.status).toBe('completed'); const p = attempt.challenge.proof; if (p.kind !== 'case') throw Error('Wrong proof.'); const final = normalize(replay(attempt.challenge.start.facelets, [...p.solution, ...(!p.finalAuf ? [] : [{ family: 'U' as const, amount: p.finalAuf === 3 ? -1 as const : p.finalAuf }])])); expect(lowerIndices.every((i) => final[i] === solved[i])).toBe(true); if (trainer === 'pll') expect(final).toBe(solved); }
  await cold.getByRole('button', { name: 'Session / history', exact: true }).click(); await cold.locator('.attempt-list summary').first().click(); await cold.getByRole('button', { name: 'Review saved attempt' }).first().click(); await expect(cold.getByRole('button', { name: 'Play', exact: true })).toBeEnabled({ timeout: 20000 });
  const latest = [...saved.value.attempts].sort((a, b) => b.endedAt.localeCompare(a.endedAt))[0]; if (!latest || latest.challenge.proof.kind !== 'case') throw Error('Missing saved review rep.');
  await expect(cold.getByTestId('player-state')).toHaveText(latest.challenge.start.facelets); for (let i = 0; i < latest.challenge.proof.solution.length + (latest.challenge.proof.finalAuf ? 1 : 0); i++) await cold.getByRole('button', { name: 'Forward', exact: true }).click(); await expect(cold.getByTestId('logical-state')).toHaveText(solved); await expect(cold.getByTestId('player-state')).toHaveText(solved); await cold.getByRole('button', { name: 'Close dialog' }).click();
  await cold.reload(); await expect(cold.getByRole('combobox', { name: 'Trainer', exact: true })).toHaveValue(trainer, { timeout: 30000 }); await expect(cold.locator('.session-dock')).toContainText(`${count} saved attempts`); expect(failures).toEqual([]); console.log(`Full ${trainer.toUpperCase()} ${count} production reps, accelerated browser clock, no physical solves. Chrome ${browser.version()}.`);
});
test('subset set/editor frozen guidance, personal pre-AUF, quota retry and linked delete/Undo/restore', async ({ page }) => {
  await page.goto('/'); await choose(page, 'pll', 2); await page.getByRole('button', { name: 'Settings', exact: true }).click(); await page.getByRole('textbox', { name: 'Set name', exact: true }).fill('Two PLL cases'); await page.getByRole('button', { name: 'Save custom set' }).click(); await expect(page.getByText('Set changes saved. Frozen runs are unchanged.')).toBeVisible(); await page.getByRole('button', { name: 'Save settings' }).click(); await expect(page.getByText('Settings saved on this device.')).toBeVisible(); await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.getByRole('button', { name: 'Personal algorithms', exact: true }).click(); const entry = PLL_CASES[0]; if (!entry) throw Error('Missing actual case.'); const source = canonicalText(entry.defaultAlgorithm);
  await expect(page.getByRole('textbox', { name: 'Personal algorithm', exact: true })).toHaveValue(source); await page.getByRole('combobox', { name: 'Algorithm pre-AUF', exact: true }).selectOption('1'); await page.getByRole('textbox', { name: 'Personal algorithm', exact: true }).fill(`U' ${source} U x`); await page.getByRole('button', { name: 'Validate algorithm' }).click(); await expect(page.getByText('Valid for this intended case. Not saved yet.')).toBeVisible(); await page.getByRole('button', { name: 'Save algorithm' }).click(); await expect(page.getByText('Algorithm saved on this device. Frozen runs are unchanged.')).toBeVisible();
  await page.getByRole('textbox', { name: 'Personal algorithm', exact: true }).fill('R'); await page.getByRole('button', { name: 'Validate algorithm' }).click(); await expect(page.getByRole('alert')).toContainText('Previous guidance and history are unchanged'); await expect(page.getByRole('button', { name: 'Save algorithm' })).toBeDisabled(); await page.getByRole('button', { name: 'Close dialog' }).click();
  await start(page, 'pll'); const planned = await backup(page); expect(planned.value.runs[0]?.snapshot?.challenges[0]?.proof).toMatchObject({ finalAuf: 3 }); await present(page);
  await page.evaluate(() => { const put = IDBObjectStore.prototype.put; IDBObjectStore.prototype.put = function (value: unknown, key?: IDBValidKey) { if (this.name === 'runs') { IDBObjectStore.prototype.put = put; throw new DOMException('Actual run transaction quota', 'QuotaExceededError'); } return key === undefined ? put.call(this, value) : put.call(this, value, key); }; });
  await page.keyboard.down('Space'); await page.waitForTimeout(330); await page.keyboard.up('Space'); await page.keyboard.press('Space'); await expect(page.getByRole('button', { name: 'Retry save' })).toBeVisible(); await expect(page.getByRole('button', { name: 'Next challenge' })).toHaveCount(0); await page.getByRole('button', { name: 'Retry save' }).click(); await expect(page.getByRole('status').filter({ hasText: 'Saved on this device' })).toBeVisible();
  const saved = await backup(page); expect(saved.value.attempts).toHaveLength(1); expect(saved.value.runs[0]?.cursor).toBe(1);
  await page.getByRole('button', { name: 'Review attempt' }).click(); await expect(page.getByText('Moves include required final AUF:', { exact: false })).toContainText("U'"); await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeEnabled({ timeout: 20000 }); const proof = saved.value.attempts[0]?.challenge.proof; if (!proof || proof.kind !== 'case') throw Error('Missing actual frozen PLL proof.'); for (let i = 0; i < proof.solution.length + 1; i++) await page.getByRole('button', { name: 'Forward', exact: true }).click(); await expect(page.getByTestId('logical-state')).toHaveText(solved); await expect(page.getByTestId('player-state')).toHaveText(solved); await page.getByRole('button', { name: 'Close dialog' }).click(); await page.getByRole('button', { name: 'Next challenge' }).click();
  await page.getByRole('button', { name: 'Personal algorithms', exact: true }).click(); await page.getByRole('button', { name: 'Use default' }).click(); await expect(page.getByText('Override removed. Future runs use the sourced default.')).toBeVisible(); await page.getByRole('button', { name: 'Close dialog' }).click(); await expect(page.getByText('Run settings and guidance remain frozen', { exact: false })).toBeVisible();
  await present(page); await execute(page); await page.getByRole('button', { name: 'Next challenge' }).click();
  await page.getByRole('button', { name: 'Session / history', exact: true }).click(); await page.locator('.attempt-list summary').first().click(); await page.getByRole('button', { name: 'Set DNF', exact: true }).first().click(); await expect(page.getByRole('region', { name: 'Attempt statistics' })).toContainText('1 DNF');
  page.once('dialog', (dialog) => dialog.accept()); await page.getByRole('button', { name: 'Delete attempt…', exact: true }).first().click(); await page.getByRole('button', { name: 'Undo latest history change' }).click(); await page.getByRole('button', { name: 'Close dialog' }).click(); const edited = await backup(page); expect(edited.value.attempts).toHaveLength(2); expect(edited.value.runs[0]?.cursor).toBe(2); expect(edited.value.runs[0]?.snapshot).toEqual(planned.value.runs[0]?.snapshot);
  await page.getByRole('button', { name: 'Settings', exact: true }).click(); await page.getByRole('checkbox', { name: 'PLL Aa ·', exact: false }).uncheck(); await page.getByRole('button', { name: 'Save custom set' }).click(); await expect(page.getByText('Set changes saved. Frozen runs are unchanged.')).toBeVisible(); await page.getByRole('button', { name: 'Save settings' }).click(); await expect(page.getByText('Settings saved on this device.')).toBeVisible(); await page.getByRole('button', { name: 'Close dialog' }).click(); const changedSet = await backup(page); expect(changedSet.value.practiceSets).toHaveLength(1); expect(changedSet.value.practiceSets[0]?.caseIds).toHaveLength(1); expect(changedSet.value.runs[0]?.snapshot).toEqual(planned.value.runs[0]?.snapshot);
  await page.getByRole('button', { name: 'Settings', exact: true }).click(); await page.getByRole('button', { name: 'Delete selected set' }).click(); await expect(page.getByText('Set changes saved. Frozen runs are unchanged.')).toBeVisible(); await page.getByRole('button', { name: 'Save settings' }).click(); await expect(page.getByText('Settings saved on this device.')).toBeVisible(); await page.getByRole('button', { name: 'Close dialog' }).click(); const deletedSet = await backup(page); expect(deletedSet.value.practiceSets).toEqual([]); expect(deletedSet.value.runs[0]?.snapshot).toEqual(planned.value.runs[0]?.snapshot);
  await dataPanel(page); await page.getByLabel('Restore backup file').setInputFiles({ name: 'real-pll.json', mimeType: 'application/json', buffer: saved.bytes }); await expect(page.getByText('Validated backup preview')).toBeVisible(); await page.getByLabel('I confirm replacement').check(); await page.getByRole('button', { name: 'Replace local data', exact: true }).click(); await expect(page.getByText('Local data replaced.')).toBeVisible(); await page.getByRole('button', { name: 'Close dialog' }).click(); await page.getByRole('button', { name: /Resume Two PLL cases/ }).click(); await expect(page.getByRole('checkbox', { name: /My cube/ })).not.toBeChecked();
});
test('reload/visibility interruption, deliberate recognition review, skip, abandonment and phone pointer input', async ({ page, context }) => {
  await page.goto('/'); await choose(page, 'oll', 3); await start(page, 'oll'); await present(page); await hidden(page); await page.reload(); await page.getByRole('button', { name: /Resume Custom OLL 3/ }).click(); await page.getByRole('button', { name: 'Recover presented rep as interrupted' }).click(); await expect(page.getByRole('checkbox', { name: /My F2L/ })).not.toBeChecked();
  await present(page); await page.setViewportSize({ width: 390, height: 844 }); const cdp = await context.newCDPSession(page); await cdp.send('Emulation.setTouchEmulationEnabled', { enabled: true }); const box = await page.locator('.timer-input').boundingBox(); if (!box) throw Error('Missing timer.'); const point = { x: box.x + box.width / 2, y: box.y + box.height / 2 };
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [point] }); await page.waitForTimeout(330); expect(await page.evaluate(() => getSelection()?.toString())).toBe(''); await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); await expect(page.getByRole('status').filter({ hasText: 'Tap to stop' })).toBeVisible();
  await page.evaluate(() => { Object.defineProperty(document, 'visibilityState', { configurable: true, value: 'hidden' }); document.dispatchEvent(new Event('visibilitychange')); }); await expect(page.getByRole('status').filter({ hasText: 'Saved on this device' })).toBeVisible(); await hidden(page); await page.getByRole('button', { name: 'Review attempt' }).click(); await expect(page.getByRole('heading', { name: /OLL 2/ })).toBeVisible(); await page.getByRole('button', { name: 'Close dialog' }).click(); await page.getByRole('button', { name: 'Next challenge' }).click();
  await page.evaluate(() => { Object.defineProperty(document, 'visibilityState', { configurable: true, value: 'visible' }); document.dispatchEvent(new Event('visibilitychange')); }); await page.getByRole('button', { name: 'Skip rep without timing' }).click(); await page.getByText('Run summary', { exact: true }).click(); await expect(page.getByRole('region', { name: 'Time Attack run results' })).toContainText('0 completed · 0 DNF · 1 skipped · 2 interrupted'); await expect(page.getByRole('region', { name: 'Time Attack run results' })).toContainText('No successful set PB');
  const saved = await backup(page); expect(saved.value.attempts).toHaveLength(1); expect(saved.value.attempts[0]?.timing.status).toBe('interrupted'); await start(page, 'oll'); page.once('dialog', (dialog) => dialog.accept()); await page.getByRole('button', { name: 'Abandon run', exact: true }).click();
});
test('strict inspection separate first action, native editor isolation and actual LL cache repair', async ({ page, context }) => {
  await setup(page); await choose(page, 'pll', 1, '15s'); await start(page, 'pll'); await page.clock.install({ time: new Date(Date.now() + 1000) }); await present(page); await hidden(page);
  await page.keyboard.press('Space'); await expect(page.locator('.timer-input')).toContainText('Hold, then release'); await page.locator('.timer-input').focus(); await page.keyboard.press('Enter'); await expect(page.locator('.timer-input')).toContainText('Hold, then release'); await page.clock.runFor(16700); await page.keyboard.down('Space'); await page.clock.runFor(330); await page.keyboard.up('Space'); await page.clock.runFor(100); await page.keyboard.press('Space'); await expect(page.getByRole('status').filter({ hasText: 'Saved on this device' })).toBeVisible(); await expect(page.locator('.attempt-result h2')).toHaveText('DNF'); const before = await backup(page);
  await context.setOffline(true); await page.evaluate(async () => { const name = (await caches.keys()).find((name) => name.startsWith('cube-trainer-assets-')); if (!name) throw Error('Missing actual cache.'); const cache = await caches.open(name), response = await cache.match('/release-assets.json'); if (!response) throw Error('Missing actual manifest.'); const manifest: { assets: { url: string }[] } = await response.json(), asset = manifest.assets.find((asset) => /ll.worker-.*\.js$/.test(asset.url)); if (!asset) throw Error('Missing actual LL worker.'); await cache.put(asset.url, new Response('corrupt actual LL bytes')); });
  await dataPanel(page); await page.getByRole('button', { name: 'Recheck cached review' }).click(); await expect(page.getByRole('status').filter({ hasText: /Offline shell incomplete:.*ll.worker/ })).toBeVisible(); await context.setOffline(false); await page.getByRole('button', { name: 'Set up / retry review' }).click(); await expect(page.getByRole('status').filter({ hasText: /OLL ready.*PLL ready/ })).toBeVisible({ timeout: 30000 }); await page.getByRole('button', { name: 'Close dialog' }).click(); expect((await backup(page)).value.attempts).toEqual(before.value.attempts);
});
test('actual plan/dialog cancellation, cross-tab settings and confirmed restore preserve run ownership', async ({ page, context }) => {
  await page.addInitScript(() => { const send = Worker.prototype.postMessage; Worker.prototype.postMessage = function (message: unknown) { if (message && typeof message === 'object' && 'kind' in message && message.kind === 'plan') setTimeout(send.bind(this, message), 500); else send.call(this, message); }; });
  await page.goto('/'); await choose(page, 'oll', 2); await page.getByRole('button', { name: 'Start OLL run', exact: true }).click(); await page.getByRole('button', { name: 'Help', exact: true }).click(); await expect(page.locator('.practice [role=alert]')).toContainText('Run start deferred'); await expect(page.getByRole('region', { name: 'Presented challenge' })).toHaveCount(0); await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.getByRole('button', { name: 'Start OLL run', exact: true }).click(); await page.getByRole('button', { name: 'Move review', exact: true }).click(); await page.getByRole('button', { name: 'Close dialog' }).click(); await expect(page.getByRole('button', { name: 'Start OLL run', exact: true })).toBeVisible(); await expect(page.getByRole('region', { name: 'Presented challenge' })).toHaveCount(0);
  await start(page, 'oll'); await present(page); await execute(page); const saved = await backup(page); await page.getByRole('button', { name: 'Next challenge' }).click();
  const other = await context.newPage(); await other.goto('/'); await choose(other, 'oll', 1); await page.bringToFront(); await page.getByRole('checkbox', { name: /My F2L/ }).check(); await page.getByRole('button', { name: 'Present next rep', exact: true }).click(); await expect(page.locator('.practice [role=alert]')).toContainText('Settings changed in another tab'); await expect(page.getByRole('region', { name: 'Presented challenge' })).toHaveCount(0);
  await dataPanel(page); await page.getByLabel('Restore backup file').setInputFiles({ name: 'real-owned-run.json', mimeType: 'application/json', buffer: saved.bytes }); await expect(page.getByText('Validated backup preview')).toBeVisible(); await page.getByLabel('I confirm replacement').check(); await page.getByRole('button', { name: 'Replace local data', exact: true }).click(); await expect(page.getByText('Local data replaced.')).toBeVisible(); await page.getByRole('button', { name: 'Close dialog' }).click(); await page.getByRole('button', { name: /Resume Custom OLL 2/ }).click(); await expect(page.getByRole('checkbox', { name: /My F2L/ })).not.toBeChecked(); const restored = await backup(page); expect(restored.value.attempts).toEqual(saved.value.attempts); expect(restored.value.runs[0]).toMatchObject({ cursor: 1, status: 'interrupted', presented: false }); await other.close();
});
test('active production LL timing blocks prepared actual update and retained run/attempt survives activation', async ({ page, context, preparedRelease }) => {
  await setup(page); await choose(page, 'oll', 2); await start(page, 'oll'); await present(page); const idle = await context.newPage(); await idle.goto('/'); await page.keyboard.down('Space'); await page.waitForTimeout(330); await page.keyboard.up('Space'); await hidden(page);
  await cp(preparedRelease, resolve('dist'), { recursive: true }); await dataPanel(idle); await idle.getByRole('button', { name: 'Check for update' }).click(); await idle.getByRole('button', { name: 'Close dialog' }).click(); await expect(idle.getByRole('button', { name: 'Apply update' })).toBeVisible({ timeout: 30000 }); idle.on('dialog', (dialog) => void dialog.accept()); await idle.getByRole('button', { name: 'Apply update' }).click(); await expect(idle.locator('.practice [role=alert]')).toContainText('other tabs');
  await page.bringToFront(); await page.keyboard.press('Space'); await expect(page.getByRole('status').filter({ hasText: 'Saved on this device' })).toBeVisible(); const before = await backup(page); await Promise.all([page.waitForEvent('load'), idle.getByRole('button', { name: 'Apply update' }).click()]); await expect(page.getByRole('button', { name: /OLL ready.*PLL ready/ })).toBeVisible({ timeout: 30000 }); await expect(page.getByRole('combobox', { name: 'Trainer', exact: true })).toHaveValue('oll'); const after = await backup(page); expect(after.value.attempts).toEqual(before.value.attempts); expect(after.value.runs).toEqual(before.value.runs);
});
