import { useState } from 'react';
import { QUARTERS } from '../cases/identity';
import { llLibrary, type LLTrainer } from '../ll/model';
import type { LLPreferences, PracticeSetRecord } from '../store/records';
import { Repository, storageMessage } from '../store/repository';
export function TimeAttackSettings({ trainer, value, sets, repository, onChange, onChanged, onBusy }: { trainer: LLTrainer; value: LLPreferences; sets: PracticeSetRecord[]; repository: Repository; onChange: (value: LLPreferences) => void; onChanged: () => Promise<void>; onBusy: (busy: boolean) => void }) {
  const [editingId, setEditingId] = useState<string | null>(value.setId);
  const [search, setSearch] = useState(''), [family, setFamily] = useState('all'), [label, setLabel] = useState(() => sets.find((set) => set.id === value.setId)?.label ?? ''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  const library = llLibrary(trainer), filtered = library.filter((entry) => (family === 'all' || entry.family === family) && `${entry.label} ${entry.family}`.toLowerCase().includes(search.toLowerCase()));
  async function mutate(action: () => Promise<void>) { setBusy(true); onBusy(true); setMessage(''); try { await action(); await onChanged(); setMessage('Set changes saved. Frozen runs are unchanged.'); } catch (error) { setMessage(storageMessage(error)); } finally { setBusy(false); onBusy(false); } }
  return <section aria-label="Time Attack set selection">
    <label>Saved set<select value={value.setId ?? ''} onChange={(event) => { const selected = sets.find((set) => set.id === event.target.value && set.trainer === trainer); onChange({ ...value, setId: selected?.id ?? null, caseIds: selected ? [...selected.caseIds] : library.map((entry) => entry.id) }); setLabel(selected?.label ?? ''); setEditingId(selected?.id ?? null); }}><option value="">Full {trainer.toUpperCase()} list</option>{sets.filter((set) => set.trainer === trainer).map((set) => <option key={set.id} value={set.id}>{set.label} · {set.caseIds.length} cases</option>)}</select></label>
    <label>Time Attack mode<select value={value.mode} onChange={(event) => { const mode = event.target.value; if (mode === 'execution' || mode === 'recognition') onChange({ ...value, mode }); }}><option value="execution">Execution</option><option value="recognition">Recognition</option></select></label>
    <label className="check"><input type="checkbox" checked={value.shuffle} onChange={(event) => onChange({ ...value, shuffle: event.target.checked })} />Shuffle set order</label>
    {(['preAuf', 'yaw'] as const).map((field) => <label key={field}>{field === 'preAuf' ? 'Setup pre-U' : 'Setup yaw'}<select value={value[field]} onChange={(event) => { const angle = event.target.value === 'random' ? 'random' : QUARTERS.find((q) => String(q) === event.target.value); if (angle !== undefined) onChange({ ...value, [field]: angle }); }}><option value="random">Random</option>{QUARTERS.map((q) => <option key={q} value={q}>{q}</option>)}</select></label>)}
    <p>{library.length} verified {trainer.toUpperCase()} cases. Select weak cases manually using per-case history. No automatic coaching. Recognition is limited to the selected pool. Each run freezes its membership, settings and guidance.</p>
    <label>Case search<input value={search} onChange={(event) => setSearch(event.target.value)} /></label>
    <label>Case family<select value={family} onChange={(event) => setFamily(event.target.value)}><option value="all">All families</option>{[...new Set(library.map((entry) => entry.family))].map((f) => <option key={f}>{f}</option>)}</select></label>
    <button type="button" onClick={() => onChange({ ...value, setId: null, caseIds: library.map((entry) => entry.id) })}>Select all {library.length}</button><button type="button" onClick={() => onChange({ ...value, setId: null, caseIds: [] })}>Clear case selection</button><button type="button" onClick={() => onChange({ ...value, setId: null, caseIds: library.filter((entry) => filtered.includes(entry) || value.caseIds.includes(entry.id)).map((entry) => entry.id) })}>Select filtered cases</button>
    <p>{value.caseIds.length} selected{value.caseIds.length ? '' : '. Select at least one case.'}</p>
    {filtered.map((entry) => <label className="check" key={entry.id}><input type="checkbox" checked={value.caseIds.includes(entry.id)} onChange={(event) => onChange({ ...value, setId: null, caseIds: library.filter((item) => item.id === entry.id ? event.target.checked : value.caseIds.includes(item.id)).map((item) => item.id) })} />{trainer.toUpperCase()} {entry.label} · {entry.family}</label>)}
    <label>Set name<input value={label} maxLength={120} onChange={(event) => setLabel(event.target.value)} /></label>
    <button type="button" disabled={busy || !label.trim() || !value.caseIds.length} onClick={() => void mutate(async () => { const current = await repository.read(), previous = current.backup.practiceSets.find((set) => set.id === editingId), now = new Date().toISOString(); const set: PracticeSetRecord = { id: previous?.id ?? crypto.randomUUID(), trainer, label: label.trim(), caseIds: [...value.caseIds], createdAt: previous?.createdAt ?? now, updatedAt: now }; await repository.savePracticeSet(set, set.id, current.revision); onChange({ ...value, setId: set.id }); setEditingId(set.id); })}>Save custom set</button>
    <button type="button" disabled={busy || !editingId} onClick={() => void mutate(async () => { const current = await repository.read(); if (!editingId) return; await repository.savePracticeSet(null, editingId, current.revision); setEditingId(null); onChange({ ...value, setId: null }); })}>Delete selected set</button>
    {message && <p role="status">{message}</p>}
  </section>;
}
